{
 "title": "Mylar3",
 "description": "Comic books ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data source", "query": "prometheus" },
   { "name": "server", "label": "Server", "query": { "query": "label_values(mylar3_up,server)" } }
  ]
 },
 "panels": [
  {
   "title": "Mylar3 Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mylar3_up{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Wanted issues",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mylar3_wanted_count{server=\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wanted issues",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(mylar3_wanted_count{server=\"$server\"})",
     "legendFormat": "{{name}} ({{year}})"
    }
   ]
  },
  {
   "title": "Total series",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mylar3_series_count{server=\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total issues",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mylar3_issues_count{server=\"$server\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Series by publisher",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(publisher) (mylar3_series_count{server=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Issues by publisher",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(publisher) (mylar3_issues_count{server=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}